### ISSUE TITLE
RMCProfile interface glitch on MacOS

### ISSUE THREAD

**Issue by Kvieta1990** [AdvancedPhotonSource/GSAS-II#106]
This is a small issue but will be better to be fixed. On MacOS, in the RMCProfile interface, when trying to import the total scattering data, either it is the real space or reciprocal space data, the imported data will only show up at the second time of importing.

**Comment by briantoby** [comment]
> This is a small issue but will be better to be fixed. 

noting that this was raised by a sometimes-APS user and RMCProfile is maintained in part by SNS.
