### ISSUE TITLE
Cannot add Excluded Regions

### ISSUE THREAD

**Issue by Te-rex83** [AdvancedPhotonSource/GSAS-II#109]
GSAS v7493c2, 23 Nov 2024, Full version, Windows 11

Using EDX data, no matter what I try, I cannot set an Excluded Region in the diffraction pattern. 
- When clicking on Add Excluded Region in the Edit Limits menu, text appears in the graphical window: 
  "Click on a point in the pattern to be excluded, then drag or edit limits to adjust range."
- However, nothing happens when clicking on the pattern (anywhere)! 
- Therefore, I cannot add Excluded Regions.

Please confirm!

**Comment by Te-rex83** [comment]
Attached is an example project to test with.
[LaB6.zip](https://github.com/user-attachments/files/17936276/LaB6.zip)

**Comment by Te-rex83** [comment]
The last version where 'add excluded regions' still works as intended is version: 76a701 (02 Nov 2024). At the time of writing, 26 version ago. I hope this helps...

**Comment by briantoby** [comment]
There are two ways to add limits. One is with the menu command described above. That is broken for CW & ED (did not try TOF) patterns. Will investigate. 

The second way to define excluded regions is to press "e" at the start of the region and then move the cursor to the end of the regions and press "e". That works for both.

**Comment by briantoby** [comment]
Your identification of 76a701c as the last version without this bug helped me located what would have otherwise been a very obscure bug and the project file allowed me to test with ED x-ray data easily. Thanks!

I had added the ability to display tickmarks on the limit plot, but in the process one of my statements broke the menu commands. This is fixed in 5e17788a.

**Comment by Te-rex83** [comment]
Thank you very much! There are other issues with ED-XRD refinements, but I need to see how to report them and if they persist in future versions of GSASII...

**Comment by briantoby** [comment]
Please do report bugs and inconveniences. If we don't know there is a problem, we are not likely to fix it. The ED x-ray sections are not widely used and the relatively few people who use them carry a bigger weight with documenting issues.
