### ISSUE TITLE
Ir-191 and Ir-193 scattering lengths available

### ISSUE THREAD

**Issue by pkienzle** [AdvancedPhotonSource/GSAS-II#110]
Hannon, A. C., Gibbs, A. S. & Takagi, H. (2018). J. Appl. Cryst. 51, 854-866.
DOI:[10.1107/S1600576718006064](https://doi.org/10.1107/S1600576718006064)

**Comment by vondreele** [comment]
191Ir & 193Ir added to atmdata.py file. Values give correct b for natural abundance Ir as in this table.
