### ISSUE TITLE
Unable to output CSV data

### ISSUE THREAD

**Issue by 111222561** [AdvancedPhotonSource/GSAS-II#116]
Unable to output CSV file on the page, resulting in an error message on the Python interface: TypeError: 'numpy. tool_' object is not iterable
How to solve such problems, I hope to reply as soon as possible
![屏幕截图 2024-12-09 233810](https://github.com/user-attachments/assets/0a8493d4-8407-402e-9665-74086316eb69)
![屏幕截图 2024-12-09 233646](https://github.com/user-attachments/assets/884f241f-3c4b-47e7-8a74-2d991d39989c)
[GSASIIpwdplot.txt](https://github.com/user-attachments/files/18064004/GSASIIpwdplot.txt)

**Comment by briantoby** [comment]
I'm not able to reproduce this with the .gpx file I have on-hand. I took a guess on a work-around, so please update and try again.

If the problem persists, could you reopen this issue send me one that reproduces your bug? (Direct e-mail to me works if you prefer.)

**Comment by 111222561** [comment]
I tried to modify the code in this file and it worked well. As a beginner, would you like to obtain a file output explanation for GSAS2? Thank you, I wish you a happy life

**Comment by briantoby** [comment]
_The text added to the help file is this:_

### Publication Plots
When the green "P" button is pressed, a copy of the current powder diffraction plot is presented in a separate window. This can only be done with plots of a single histogram. Not for waterfall or contour plots. The separate plot offers GUI controls to modify aspects of the plot, for example by changing colors, line widths, plot limits the contents or size of displayed text. The displayed plot, including any changes made, can be exported in a number of formats. These include a number of bitmap formats (JPEG, PNG, TIFF,...) that can then be imported into other programs; several formats offer vector graphics (Postscript, PDF, SVG), that will render at whatever resolution is desired, which can be of great value for posters or other applications where pixilation would be problematic; other formats are intended to be read into other software: Input for the [Grace](https://en.wikipedia.org/wiki/Grace_(plotting_tool)), Igor Pro and Origin programs is offered, as well as a generic .csv file that can be used with custom software. Note that Igor Pro and Origin are commercial products. (Origin export is only available on Windows and requires that Origin 2021 or later be installed on the computer where GSAS-II is installed. The [Grace](https://en.wikipedia.org/wiki/Grace_(plotting_tool)) program is open-source, runs on all major computing platforms, and is available in several versions. The .csv file consists of 10 or more columns (depending on the number of phases included in the histogram). The columns are described below, noting that N is the total number of phases and if there are M data points in the histogram, will be M datapoints in each column except in the Phase, tick-pos, and Axis-limits columns.

- 1: Used:
Indicates if the data point is inside the plot limits or is excluded from the fit. A value of 1 means the values are used and 0 means the data point is not used.
- 2: X:
The x-values from the plot in the units used in the plot (2theta, Q,...). The units are noted in the header.
- 3: Obs:
The observed diffraction intensity. This may be modified by scaling options or background subtraction, if that has been selected for the plot.
- 4: Calc:
The computed diffraction intensity. This will usually be zero if "Used" is 0.
- 5: Bkg:
The computed background value at the current "X" location, This will usually be zero if "Used" is 0.
- 6: Diff:
The plotted difference curve. This will have the offset used in the plot.
- 6+I: Phase i:
This has the reflection positions (tickmarks) in the same units as used for "X". There will be far fewer values for this than for the previous columns.
- 7+N: tick-pos:
The name of each phase followed by the vertical position used to display the tickmarks for each phase. There will be 2N of these values.
- 8+N: diff/sigma:
The uncertainty-weighted difference plot [(Obs-Calc)/sigma where sigma is the statistically expected uncertainty in the obs values, i.e. the standard uncertainty values]. Note that values where "Used" is 0 are meaningless, as the Calc value is 0, but the Obs and sigma values are from the data.
- 9+N: Axis-limits:
Has four values, x-min, x-max, y-min and y-max as used as the limits for the plot.
