### ISSUE TITLE
Revert the changes to He_, Ar_, Kr_, and Xe_

### ISSUE THREAD

**Issue by pkienzle** [AdvancedPhotonSource/GSAS-II#120]
Re: #84 the Haddock paper gives total scattering cross section, not scattering length. You could use these to update your SA values but not your SL values. Please revert the changes to He_, Ar_, Kr_, and Xe_.

With the update to He_4, your He_ will now be inconsistent with He_4.  Instead I use the weighted average = 3.0985.

For Kr, σ_tot is inconsistent with σ_inc and b_c, even after update:
```
σ_tot=7.685
σ_inc=0.01
σ_tot-4π|b_c|²/100=0.019997940034326867

b_c=(7.81-0.006952169076751946j)
σ_coh=7.67
4π|b_c|²/100=7.665002059965673
```
For Xe the inconsistency is larger:
```
σ_tot=4.344
σ_inc=0.0
σ_tot-4π|b_c|²/100=1.5798830023579238

b_c=(4.69-0.006646273637374861j)
σ_coh=3.04
4π|b_c|²/100=2.7641169976420765
```
For Ar the paper says the existing values are more accurate so I didn't update:
```
σ_tot=0.683
σ_inc=0.225
σ_tot-4π|b_c|²/100=0.2250461388836269

b_c=(1.909-0.00018770856507230256j)
σ_coh=0.458
4π|b_c|²/100=0.45795386111637315
```

And He for completeness:
```
σ_tot=1.2065
σ_inc=0.0
σ_tot-4π|b_c|²/100=4.0173683337974e-05

b_c=(3.0985-2.0773081201334816e-06j)
σ_coh=1.2065
4π|b_c|²/100=1.206459826316662
```

When computing incoherent scattering for compounds I'm using b_c and σ_tot, not σ_inc which is why I left the σ_inc values unchanged.

_Originally posted by @pkienzle in https://github.com/AdvancedPhotonSource/GSAS-II/issues/84#issuecomment-2555975231_

**Comment by vondreele** [comment]
Hi,
I have changed Scattering length data for the "noble" gases back to what is in the "Neutron Data Booklet". hard to know what neutron experiment would need them apart from Xe & perhaps Kr as they do form compounds (with F & O) but very limited.
You should close #120.
Bob
________________________________

**Comment by vondreele** [comment]
atmdata.py fix is in indexing branch not master.
________________________________

**Comment by briantoby** [comment]
copied to master from indexing in da8cd425.
