### ISSUE TITLE
Only 1 exclusion region can be added at a time

### ISSUE THREAD

**Issue by miyesven** [AdvancedPhotonSource/GSAS-II#23]
Hi 
I am using GSAS to process some synchotron data with high background from the sample holder. I am trying to hone in on some key regions by excluing the rest but it seems like only one region can be excluded at a time. I just updated to the latest version but this is still an issue. I'm not sure if I am doing anything wrong or if this is a bug. Thanks for looking into it. Attached is my GSAS project with the 3 excluded regions.
[gsas_exclusionbug.zip](https://github.com/AdvancedPhotonSource/GSAS-II/files/15382638/gsas_exclusionbug.zip)

**Comment by briantoby** [comment]
Your .gpx file has three excluded regions:
<img width="542" alt="image" src="https://github.com/AdvancedPhotonSource/GSAS-II/assets/9433704/2357e60d-cc5a-4a32-86ef-1db58787ac78">

In fact, most of your diffraction pattern is excluded (by pressing the x key):
<img width="362" alt="image" src="https://github.com/AdvancedPhotonSource/GSAS-II/assets/9433704/254d57d6-8b5b-4f29-a43b-d8e4805f1feb">

No doubt we could do a better job with the UI in how to create and manage excluded regions. How are you trying to create them? Would this be better continued via Zoom or e-mail (toby at ANL dot gov)? 

Brian

**Comment by miyesven** [comment]
Hi Brian,
Thank you for the quick reply. My issue is really that the auto search function in the peak fitting section is still including the excluded regions. But I will follow up by email.

**Comment by briantoby** [comment]
excluded regions are intended only to be used for Rietveld fits. Not for peak fitting. Peak fitting can be done in sections by changing the data limits and can thus avoid spurious sections of a pattern. Or one can just add, fit and then ignore peaks in those spurious regions.
