### ISSUE TITLE
Problem with constraint equation

### ISSUE THREAD

**Issue by MaegL** [AdvancedPhotonSource/GSAS-II#27]
Good day,

I cannot constrain the phase fraction by constraint equation. The error is as follows in the image.

![image](https://github.com/AdvancedPhotonSource/GSAS-II/assets/170983099/b8cd8619-429f-4be0-a441-61941e28059e)

Thank you for the help!

**Comment by briantoby** [comment]
That message is saying that the constraint equation has been stored, but will not be used until you set the refinement flag for the two scale factors

**Comment by briantoby** [comment]
I am wondering if there is a better way to word this warning

**Comment by MaegL** [comment]
I am not sure, I am a fresh user of GSAS II, but maybe knowing that the constraint is actually valid and can be used for the refinement could help.

Thank you again.

**Comment by briantoby** [comment]
The warning message here has been softened a bit. Perhaps that will help.
