### ISSUE TITLE
Can not import pyspg

### ISSUE THREAD

**Issue by HelloAI-twj** [AdvancedPhotonSource/GSAS-II#49]
Hello, I meet a problem when I try to run the source code. I compiled the binary files by myself. but when I run the GSASII.py, It says that the pyspg module cannot be imported. The detailed error message is: 

Failed to run pyspg in 'd:\\code\\GSAG-II-5788\\bin'
error: DLL load failed while importing pyspg

The GSASII verson is 5788 and my computer is win10. 
I would like to know how to fix this problem and look forward to your reply.

**Comment by briantoby** [comment]
I really don't recommend trying to build for yourself for windows, but if you insist, you should try running Python and then perform the command "import pyspg" and see what error message you get.

**Comment by briantoby** [comment]
anything new here?

**Comment by briantoby** [comment]
closed until more info is provided
