### ISSUE TITLE
SFAC line that ends in "=" in G2phase_INS.py causes failure

### ISSUE THREAD

**Issue by davidelbert** [AdvancedPhotonSource/GSAS-II#52]
Student reports that the file https://github.com/AdvancedPhotonSource/GSAS-II/blob/master/GSASII/imports/G2phase_INS.py has a fatal flaw when it encounters an SFAC line that ends in "=" 

Here's a quick fix to make it keep going:
            elif S[:4].upper() in 'SFAC' or SFACcontinue:
                aTypes = S[4:].split()
                if 'H' in aTypes:
                    self.warnings += '\n\nHydrogen atoms found; consider replacing them with stereochemically tied ones'
                    self.warnings += '\nas Shelx constraints & HFIX commands are ignored.'
                    self.warnings += "\nDo 'Edit/Insert H atoms' in this phase's Atoms tab after deleting the old ones."
                if "=" in aTypes:
                    SFACcontinue = True
                else:
                    SFACcontinue = False

**Comment by briantoby** [comment]
Thanks for the bug report -- particularly one with a fix. Can you attach the patched file here? Getting a SHELX file that fails without the change would also be helpful.

**Comment by briantoby** [comment]
Change completed in by Bob 8c87f1f

**Comment by davidelbert** [comment]
Wow!  Quicker that we could attach files!  Fantastic and thank you.  And props to Evan Crites at JHU for the actual info that I filed on.
