### ISSUE TITLE
PDB or PDBx/mmCIF to powder diffraction pattern?

### ISSUE THREAD

**Issue by candiedhaw** [AdvancedPhotonSource/GSAS-II#80]
I am currently working on a project that involves comparing our protein single crystal X-ray diffraction (XRD) pattern with a simulated XRD pattern of a similar protein available in the PDB database. Specifically, I am interested in the protein with PDB ID: 4KX6.
 
Could you please provide guidance on how I might achieve this comparison?
 
Thank you for your time and assistance.

**Comment by briantoby** [comment]
I'd suggest that you start looking at this tutorial: https://advancedphotonsource.github.io/GSAS-II-tutorials/Simulation/SimTutorial.htm

What will change in working with a protein is that you will use the phase importer on a file from the PDB. The old PDB format should work. I'm not sure if mmCIFs work or not. You want to simulate a longer wavelength high resolution instrument. The 0.7 A synchrotron instrument parameters seem like a good choice.

**Comment by vondreele** [comment]
GSAS-II can read in PDB format protein structures and can read single crystal data sets. It will not generate simulated single crystal data - only powder data. However, having read in both single crystal data sets, you can make a simulated powder pattern from each set of structure factors - from Reflection list, do Plot 1D hkls; this makes a stick diagram of the intensities which could be used for your comparison.

**Comment by briantoby** [comment]
@candiedhaw: I'll close this, but feel free to reopen if you have more questions
