### ISSUE TITLE
check natural Cd value for b0 in atmdata.AtmBlens

### ISSUE THREAD

**Issue by pkienzle** [AdvancedPhotonSource/GSAS-II#83]
While implementing the equations for energy dependent neutron scattering lengths  from von Dreele (2024) [DOI:[10.1107/S1600576724005375](https://doi.org/10.1107/S1600576724005375)] I was unable to find b0 values for isotopes in Table I that are missing from Table II (103-Rh, 113-Cd, 239-Pu, 240-Pu) and similarly for natural abundance.

I was able to find them in `GSASII.atmdata.AtmBlens` here:
https://github.com/AdvancedPhotonSource/GSAS-II/blob/e82b777cd7893c2e66b081738f2d7aa0269616b3/GSASII/atmdata.py#L2241-L2245

Cross checking the values from Eq 3 at 25 mEv  for all elements against values from ATI tablulated [here](http://www.ati.ac.at/~neutropt/scattering/Scattering_lengths_table_20010419.pdf) they usually agree within 10% or so, but natural Cd is very different:
```txt
nat Cd b_c   4.830  -0.701  σ_a    2520.000
    =>       0.504  -0.695         2498.787

113-Cd b_c  -8.000  -5.729  σ_a   20600.000
    =>      -6.809  -5.685        20443.386
```

Matching the Re{b_c} value requires a value of b0 = 0.6426 rather than b0 = 0.210 in the GSAS code. 

The Im{b_c} = –0.701 from the ATI tables comes from the thermal cross section σ_a / (2 λo) at λo = 1.798 Å, after correcting for units. This matches the b'' from Eq 3.

The complete comparison with the ATI tables is below. The b'' values for nat Yb and 239-Pb are also very different, but for those the ATI values are significantly different from the values in Sears.
```txt
nat Rh b_c   5.900  -0.040  σ_a     144.800
    =>       5.262  -0.040          145.336

103-Rh b_c   5.900  -0.040  σ_a     144.800
    =>       5.262  -0.040          145.336

nat Cd b_c   4.830  -0.701  σ_a    2520.000
    =>       0.504  -0.695         2498.787

113-Cd b_c  -8.000  -5.729  σ_a   20600.000
    =>      -6.809  -5.685        20443.386

nat Sm b_c   0.766  -1.644  σ_a    5910.919
    =>       0.643  -1.504         5408.961

149-Sm b_c -19.255 -11.804  σ_a   42448.548
    =>     -20.149 -10.827        38935.488

nat Eu b_c   7.160  -1.237  σ_a    4448.110
    =>       7.061  -1.137         4088.055

151-Eu b_c   6.363  -2.488  σ_a    8946.394
    =>       6.232  -2.353         8462.466

nat Gd b_c   5.479 -13.723  σ_a   49348.717
    =>       5.477 -13.739        49406.892

155-Gd b_c   5.929 -16.849  σ_a   60590.156
    =>       5.935 -16.862        60634.001

157-Gd b_c  -1.120 -71.487  σ_a  257067.219
    =>      -1.250 -71.353       256586.655

nat Er b_c   8.114  -0.040  σ_a     143.840
    =>       8.110  -0.038          137.510

167-Er b_c   3.836  -0.176  σ_a     633.066
    =>       3.838  -0.167          598.735

nat Yb b_c  12.356  -0.020  σ_a      71.920
    =>      12.263  -0.001            3.970

168-Yb b_c  -4.098  -0.629  σ_a    2261.681
    =>      -4.028  -0.645         2319.819

176-Lu b_c   6.063  -0.574  σ_a    2065.633
    =>       5.981  -0.532         1912.264

239-Pu b_c   7.700  -0.283  σ_a    1017.300
    =>       8.152  -0.152          547.856

240-Pu b_c   3.500  -0.081  σ_a     289.600
    =>       3.742  -0.078          282.233
```

**Comment by pkienzle** [comment]
Alternatively, defining b0 from the weighted sum of the b_c for elements with natural abundance and scaling b0 for 113-Cd by its abundance I get a b0 value for natural = 0.657, yielding
```txt
nat Cd b_c   4.830  -0.701  σ_a    2520.000
    =>       4.974  -0.695         2498.787
```

**Comment by vondreele** [comment]
The coefficients for 113Cd have been chosen to visually match as best as possible the variation in b0, b' & b" shown in Fig 2. in paper by Ramaseshan (see reference in paper by Von Dreele). The values for natural abundance Cd are scaled from this. One can visualize these curves in GSAS-II with the PlotXNFF utility (see the Calculate menu).

**Comment by pkienzle** [comment]
The resonance parameters for 113-Cd from Mughabghab (1984) are reasonable, but the calculated values for scattering lengths (nat-Cd b_c = 0.50 fm and 113-Cd b_c = -6.81) don't match those measured at thermal energy (nat-Cd b_c = 4.83(5) fm and 113-Cd b_c = -8.0(1) fm) from [Knopf (1995)](http://dx.doi.org/10.1007/BF01299763).

To get the GSAS-II calculated values I modified PlotXNFF as follows:
```python
bp0, bpp0 = np.interp(1.798, lams, bp[0]), np.interp(1.798, lams, bpp[0])
print(f"{isotope} b_c = {10*bp0:5.2f}{10*bpp0:+5.2f}j fm")
```

Note: recent measurements ([Volev, 2013](http://dx.doi.org/10.1016/j.nimb.2013.01.030) Table 4) give slightly updated resonance values for 113-Cd:

    E0=178.70(10), Γ=113.5(1), gΓm = 0.4800(15), giving Re=260.7(8) and Im=14794(48)

**Comment by pkienzle** [comment]
With the Volev resonance parameters I set natCd b0=0.6657 and 113Cd b0=0.6949 to match thermal values from Knopf.

The thermal σ_a values corresponding to b'' are 2430 for natCd and 19887 for 113Cd, compared to 2520 and 20600 respectively in the ATI tables.
