### ISSUE TITLE
Updated neutron bound coherent measurements 

### ISSUE THREAD

**Issue by pkienzle** [AdvancedPhotonSource/GSAS-II#84]
There are some newer measurements of scattering lengths using neutron interferometry. I haven't decided yet if I'm going to include them in periodictable.

```txt
    H-1 b_c -3.7423(12) => -3.7395(11) [1]
    H-2 b_c 6.674(6) => 6.6681(27) [1]
    He total 1.34(2) => 1.188(5) [5]
    He-4 b_c 3.26(3) => 3.0982(21) [3] (see also [5], which gives 3.075(6))
    C-12 b_c 6.6535(14) => 6.6472(9) [1]
    O-16 b_c 5.805(5) => 5.8037(29) [1]
    O-17 b_c 5.6(5) => 5.867(4) [2]
    O-18 b_c 5.84(7) => 6.009(5) [2]
    Ar total 0.683(4) => 0.683(5) [5] (existing value is more precise)
    Kr total 7.68(13) => 7.685(26) [5]
    Sn-119 b_c 6.28(3) => 6.2239(13) [1]
    Xe total --- => 4.344(17) [5]
    Sm-154 b_c 8.0(1.0) => 8.97(6) [4]
    Eu-153 b_c 8.22(12) => 8.85(3) [4]
    Pb-207 b_c 9.286(16) => 9.4024(13) [1]
    Bi-209 b_c 8.532(2) => 8.5242(18) [1]

    [1] Snow (2020) 10.1103/PhysRevD.101.062004
    [2] Fischer (2012) 10.1088/0953-8984/24/50/505105
    [3] Haun (2020) 10.1103/PhysRevLett.124.012501
    [4] Kohlmann (2016) 10.1515/zkri-2016-1984
    [5] Haddock (2019) 10.1103/PhysRevC.100.064002
```

**Comment by vondreele** [comment]
Many thanks. I can update the b-len tables with these.

**Comment by vondreele** [comment]
Pretty minor changes in some b-lengths. I'll use them.
________________________________

**Comment by pkienzle** [comment]
With the new value for 4He b_c scattering length, the isotopically weighted natHe b_c scattering length is inconsistent with the existing value, and should also be updated.

**Comment by pkienzle** [comment]
To clarify, the Haddock paper gives total scattering cross section, not scattering length. You could use these to update your SA values but not your SL values. Please revert the changes to He_, Ar_, Kr_, and Xe_.

With the update to He_4, your He_ will now be inconsistent with He_4.  Instead I use the weighted average = 3.0985.

For Kr, σ_tot is inconsistent with σ_inc and b_c, even after update:
```
σ_tot=7.685
σ_inc=0.01
σ_tot-4π|b_c|²/100=0.019997940034326867

b_c=(7.81-0.006952169076751946j)
σ_coh=7.67
4π|b_c|²/100=7.665002059965673
```
For Xe the inconsistency is larger:
```
σ_tot=4.344
σ_inc=0.0
σ_tot-4π|b_c|²/100=1.5798830023579238

b_c=(4.69-0.006646273637374861j)
σ_coh=3.04
4π|b_c|²/100=2.7641169976420765
```
For Ar the paper says the existing values are more accurate so I didn't update:
```
σ_tot=0.683
σ_inc=0.225
σ_tot-4π|b_c|²/100=0.2250461388836269

b_c=(1.909-0.00018770856507230256j)
σ_coh=0.458
4π|b_c|²/100=0.45795386111637315
```

And He for completeness:
```
σ_tot=1.2065
σ_inc=0.0
σ_tot-4π|b_c|²/100=4.0173683337974e-05

b_c=(3.0985-2.0773081201334816e-06j)
σ_coh=1.2065
4π|b_c|²/100=1.206459826316662
```

When computing incoherent scattering for compounds I'm using b_c and σ_tot, not σ_inc which is why I left the σ_inc values unchanged.
