### ISSUE TITLE
Draw Options Additional Controls not appearing (combined x-ray neutron refinement tutorial)

### ISSUE THREAD

**Issue by jmoon-uran** [AdvancedPhotonSource/GSAS-II#85]
Following the official GSAS II tutorial for combined X-ray and Neutron powder diffraction data, I got to step 10 to find that the 'draw options' controls were stuck in an overlapping box in the interface window (see in image). Tried updating GSAS II to the latest version, restarting it, starting the tutorial from scratch, making sure it was a saved file - nothing got those controls to appear. 

![NXPbSO4_2_drawoptionsbug](https://github.com/user-attachments/assets/54ab78d7-9a5d-4ee1-b915-2d6488414593)

**Comment by briantoby** [comment]
could you show the error messages listing in the console window?

**Comment by jmoon-uran** [comment]
> could you show the error messages listed in the console window? Posting the .gpx file might also help (attach it as a .zip file)

Hi Brian, thanks for responding. Here's what the console says: list indices must be integers or slices, not str. 

AFAIK I haven't tried to set any sizes or anything differently, I've literally just followed the steps of the tutorial. 

Thanks again! 
[NXPbSO4_zipped.zip](https://github.com/user-attachments/files/17450912/NXPbSO4_zipped.zip)
![NXPbSO4_2_drawoptionsbug_console](https://github.com/user-attachments/assets/d01d8bef-7e9f-47c3-a801-f13e21342358)

**Comment by briantoby** [comment]
This was easy to find armed with this:
![image](https://github.com/user-attachments/assets/153960cc-d4bb-4274-83f2-0ad8c3117420) 
as it shows me what line of code is triggering the error.

Having your ,gpx file allowed me to quickly confirm that my change addressed the bug without having to repeat the tutorial. Thanks for both and for reporting the problem.

**Comment by jmoon-uran** [comment]
Thank you Brian! Can confirm after updating this now works and appears with all the controls, I appreciate it!
![image](https://github.com/user-attachments/assets/9b6b8101-c15c-4d23-9887-304de947527b)
