### ISSUE TITLE
Error when loading instrument parameters

### ISSUE THREAD

**Issue by cjbrew** [AdvancedPhotonSource/GSAS-II#86]
An instrument parameter file which worked a few weeks ago now no longer works. The data can be loaded, but the instrument parameters do not show up in the interface. Then, when I try to load my CIF data, I receive another error message and the software stalls out. Thank you for any help you can provide here!

Here is the terminal window:

GSAS-II binary directory: C:\Users\BrewConor\gsas2full\GSAS-II\GSASII-bin\win_64_p3.11_n1.26
Python/module versions loaded:
  Python:     3.11.9  from C:\Users\BrewConor\gsas2full\python.exe.
  wx:         4.2.1
  matplotlib: 3.8.4
  numpy:      1.26.4
  scipy:      1.13.0
  OpenGL:     3.1.6
  Image:      10.3.0 (PIL or Pillow)
  Platform:   win32 64bit AMD64
  GSAS-II:    73cdb9, 22-Oct-2024 13:53 (1.0 days old). Last tag: #5798
Import path not found - set to current directory
Inconsistent step size for Rigaku .txt file on line 9 here 0.005199999999999982 prev 0.005099999999999993
Skipping header line  Column3   Column5

Skipping header line  TwoTheta  LYNXEYE_XE_T(ScanCounter)

Skipping header line  [°]       [Counts]

Read powder data PWDR Data.xy.txt from file C:\Users\BrewConor\OneDrive - ULRI-ULSE\PXRD Raw Data\D8-ADVANCE\XRD group\Sandbox\CB Refinement practice\GSAS-II Troubleshooting\Data.xy.txt (format: Topas xye/qye or 2th Fit2D chi/qchi). Inst parameters from GSAS-II file C:\Users\BrewConor\OneDrive - ULRI-ULSE\PXRD Raw Data\D8-ADVANCE\XRD group\Sandbox\CB Refinement practice\GSAS-II Troubleshooting\Refinement params.instprm
Traceback (most recent call last):
  File "C:\Users\BrewConor\gsas2full\GSAS-II\GSASII\GSASIIdataGUI.py", line 1896, in OnImportPowder
    Ymin = np.min(rd.powderdata[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BrewConor\gsas2full\Lib\site-packages\numpy\core\fromnumeric.py", line 2953, in min
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BrewConor\gsas2full\Lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zero-size array to reduction operation minimum which has no identity
Read phase component-1 from file C:\Users\BrewConor\OneDrive - ULRI-ULSE\PXRD Raw Data\D8-ADVANCE\XRD group\Sandbox\CB Refinement practice\GSAS-II Troubleshooting\component 1.cif
Traceback (most recent call last):
  File "C:\Users\BrewConor\gsas2full\Lib\site-packages\wx\core.py", line 3427, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BrewConor\gsas2full\GSAS-II\GSASII\GSASIIdataGUI.py", line 8550, in SelectDataTreeItem
    G2phG.UpdatePhaseData(G2frame,item,data)
  File "C:\Users\BrewConor\gsas2full\GSAS-II\GSASII\GSASIIphsGUI.py", line 16691, in UpdatePhaseData
    if any('X' in item for item in G2frame.GetHistogramTypes()):
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BrewConor\gsas2full\GSAS-II\GSASII\GSASIIdataGUI.py", line 5104, in GetHistogramTypes
    Inst = self.GPXtree.GetItemPyData(GetGPXtreeItemId(self,item,'Instrument Parameters'))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BrewConor\gsas2full\GSAS-II\GSASII\GSASIIctrlGUI.py", line 130, in GetItemPyData
    return wx.TreeCtrl.GetItemData(self,treeId)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TreeCtrl.GetItemData(): argument 2 has unexpected type 'int'
Traceback (most recent call last):
  File "C:\Users\BrewConor\gsas2full\GSAS-II\GSASII\GSASIIdataGUI.py", line 1307, in OnImportPhase
    Inst = self.GPXtree.GetItemPyData(GetGPXtreeItemId(self,Id,'Instrument Parameters'))[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BrewConor\gsas2full\GSAS-II\GSASII\GSASIIctrlGUI.py", line 130, in GetItemPyData
    return wx.TreeCtrl.GetItemData(self,treeId)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TreeCtrl.GetItemData(): argument 2 has unexpected type 'int'

Here are the files you will need:
[GSAS-II Troubleshooting.zip](https://github.com/user-attachments/files/17497091/GSAS-II.Troubleshooting.zip)

**Comment by briantoby** [comment]
Thanks for reporting this and supplying all the troubleshooting info.

The problem I see here is that the datafile has slightly inconsistent step sizes due to roundoff in the final digit of the two-theta value (not the instrument parameter file). GSAS-II was rejecting this as a Rigaku file because the step size varies between 0.0051 and 0.0052 and then using a different importer (the TOPAS importer). GSAS-II now works fine with unequally stepped data, and in any case these steps are so close that I don't think there is a problem so I addressed this in the Rigaku importer in update e52c1b1b. The TOPAS importer was also unable to read your file, but was leaving you with an invalid .gpx file (will track this down next.) I think the invalid .gpx file caused the rest of your problems. 

FWIW it is better to specify the importer, rather than use "Guess", particularly when having problems. 

I also was having problems reading the file on the Mac due to an invalid Unicode character for the degree symbol. This did not seem to be a problem on Windows, but I addressed that in the Rigaku importer too. 

I will close this, but feel free to re-open if your problems are not addressed.

**Comment by cjbrew** [comment]
Thank you for your prompt response! This seems to have resolved my initial issue, but another has come up. I've tried loading my data into a blank project 
using a wide range of different formats, but each time I get an error saying that there are unequal X and Y lengths in the file I tried uploading. I'm attaching some of these files for your reference; in many cases, nothing shows up in the terminal window but I'll drop in what I have:

[GSAS-II Troubleshooting Pt 2.zip](https://github.com/user-attachments/files/17498615/GSAS-II.Troubleshooting.Pt.2.zip)

=========================================================================
               General Structure Analysis System-II
             by Robert B. Von Dreele and Brian H. Toby
             Argonne National Laboratory(C), 2006-2014
 This product includes software developed by the UChicago Argonne, LLC,
            as Operator of Argonne National Laboratory.
                           Please cite:
     B.H. Toby and R.B. Von Dreele, J. Appl. Cryst. 46, 544-549 (2013)
 + other papers for DIFFax, small angle, Bilbao, ISODISTORT,... as shown
=========================================================================

C:\Windows\system32>call C:\Users\BrewConor\gsas2full\Scripts\activate
GSAS-II binary directory: C:\Users\BrewConor\gsas2full\GSAS-II\GSASII-bin\win_64_p3.11_n1.26
7 values read from config file C:\Users\BrewConor\gsas2full\GSAS-II\GSASII\config.py
Python/module versions loaded:
  Python:     3.11.9  from C:\Users\BrewConor\gsas2full\python.exe.
  wx:         4.2.1
  matplotlib: 3.8.4
  numpy:      1.26.4
  scipy:      1.13.0
  OpenGL:     3.1.6
  Image:      10.3.0 (PIL or Pillow)
  Platform:   win32 64bit AMD64
  GSAS-II:    e3781b, 23-Oct-2024 15:50 (0.0 days old). Last tag: #5798
Import path not found - set to current directory
Import path not found - set to current directory
The Panalytical xrdml (xml) reader was not able to read file C:\Users\BrewConor\OneDrive - ULRI-ULSE\PXRD Raw Data\D8-ADVANCE\XRD group\Sandbox\CB Refinement practice\MIL 160 11.6% MOF-303 Chemspeed.xrdml



Error message(s):

  Panalytical xrdml (xml) validator error: Bad xml file
Sorry, this is a Version 4 Bruker file. We need documentation for it so that it can be implemented in GSAS-II. Use PowDLL (http://users.uoi.gr/nkourkou/powdll/) to convert it to ASCII xy.
The Bruker RAW ver. 4 reader was not able to read file C:\Users\BrewConor\OneDrive - ULRI-ULSE\PXRD Raw Data\D8-ADVANCE\XRD group\Sandbox\CB Refinement practice\MIL 160 11.6% MOF-303 Chemspeed_exported.raw



Error message(s):

  Bruker RAW ver. 4 validator error: Sorry, this is a Version 4 Bruker file. We need documentation for it so that it can be implemented in GSAS-II. Use PowDLL (http://users.uoi.gr/nkourkou/powdll/) to convert it to ASCII xy.


I've downloaded PowDLL and tried using it to convert file types, with no success so far.

**Comment by briantoby** [comment]
try the latest version...

**Comment by briantoby** [comment]
The second error was a pretty dumb one. Mine.
