### ISSUE TITLE
Enhance Reader Methods to Automatically Import Pressure Metadata

### ISSUE THREAD

**Issue by dyrguez9** [AdvancedPhotonSource/GSAS-II#95]
From my recent experience working with GSAS powder data files (e.g., .gsa, .fxye, .xye), GSAS reads temperature from comments but does not automatically read pressure values. In HP experiments where temperature and pressure change, it would be extremely beneficial to recognize and import pressure data without requiring manual input. It's very painful when having thousands of data.

I implemented a solution by modifying the Reader method in G2pwd_fxye.py and G2pwd_xye.py (the only two files I need) to read lines like # Pressure (MPa) = 0.5324 from comments. This extracted value is then stored in self.Sample['Pressure'], displaying it in the Sample Parameters tab.

Could you consider adding this small modification to the code for future versions? It has no downside and would save hours of manually entering pressures.

Thank you!

Just 3 lines are added:

```
# scan comments for temperature and pressure
Temperature = 300.
Pressure = 0.1

for S in self.comments:
    if 'Temp' in S.split('=')[0]:
        Temperature = float(S.split('=')[1])
    elif 'Pressure' in S.split('=')[0]:          ##New line for pressure
        Pressure = float(S.split('=')[1])     ##New line for pressure

self.Sample['Temperature'] = Temperature
self.Sample['Pressure'] = Pressure        ##New line for pressure

```

**Comment by briantoby** [comment]
@dyrguez9 Thanks!
